### ISSUE TITLE
Module not Found

### ISSUE THREAD

**Issue by Yasaka7** [MeViMo/youbit#15]
I try installing it on windows with python version 3.10.2. i used pip install youbit and it installed it but if i want to run it i get the following error:
![grafik](https://user-images.githubusercontent.com/34037326/224747871-9b5082a3-fa70-49d9-8bf1-4b0b31e07ba2.png)

im not very experienced with python so i dont really know what to do to make it work.

**Comment by flonle** [comment]
Did you have GCC installed prior to installation? This error happens when the Cython extension in YouBit was not compiled.
