### ISSUE TITLE
Large Video Size.

### ISSUE THREAD

**Issue by Rajjco** [MeViMo/youbit#2]
Is it possible to compress the mp4 file without ruining the encoded file?

**Comment by MeViMo** [comment]
I'm not sure what you mean. The output video is compressed already before being uploaded to YouTube, by the video codec. This can be controlled through the `crf` parameter.

**Comment by Rajjco** [comment]
Well encoding a 2gb file results into a 15gb mp4 file output. I'm trying to figure out if the mp4 size can be reduced in anyway.

Would appreciate your input.

**Comment by MeViMo** [comment]
Well, reducing the size of the output video in comparison with the input file is the entire challenge. We'll call this information density. You can about double the information density by enabling the `zero_frame` option and setting the  `bpp` to 2, although you'd have to try it out and see if you can still successfully decode it.
