### ISSUE TITLE
I just uploaded and this is happening

### ISSUE THREAD

**Issue by dontbanmeplz** [MeViMo/youbit#4]
RuntimeError: This video was encoded using the VP9 codec. This might be because
the video in question got alot of views. YouBit currently cannot decode this
properly.

**Comment by MeViMo** [comment]
That's strange, I never once had a VP9-encoded video during development. I only just added this exception because the 'YouBit Example' video got re-encoded with VP9 because of its views. Can you link me the video URL that caused this?

**Comment by MeViMo** [comment]
I added support for VP9 encoded videos in [a0834c6](https://github.com/MeViMo/youbit/commit/a0834c62111f9d83a8cb614013a05e5df15c6546).
Upgrade to youbit==0.1.3 to resolve.
