### ISSUE TITLE
TypeError When using encode

### ISSUE THREAD

**Issue by Ramin-RX7** [MeViMo/youbit#8]
When I try to encode my file with this code:
    
    from youbit import Encoder
    with Encoder('C:/myfile.txt') as encoder:
        path = encoder.encode('C:/mydirectory/')  # Saves output in 'C:/mydirectory'. Defaults to current working directory.
        print(path)

which is one of the examples mentioned, I get this error:
    TypeError: unsupported operand type(s) for /: 'str' and 'str'

Solution is in line 198 in "yb.py"
You need to change
    output = directory / ("YOUBIT-" + self.metadata["filename"])
to:
    output = directory +"/"+ ("YOUBIT-" + self.metadata["filename"])

**Comment by MeViMo** [comment]
Fixed in [f1daab7](https://github.com/MeViMo/youbit/commit/f1daab7c78b41cfac04a0bda9703e05c47d2a7df).
Note that this change is not yet on PyPi.
